name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Action checkout
        uses: actions/checkout@v4

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Installing dependencies
        run: cd lib/js-sdk && yarn

      - name: tsc Linting
        run: cd lib/js-sdk && yarn lint

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: cd lib/js-sdk && yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token2 }}
          NODE_AUTH_TOKEN: ${{secrets.npm_token2}}
