name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action checkout
        uses: actions/checkout@v4

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Installing dependencies
        run: cd lib/js-sdk && yarn

      - name: tsc Linting
        run: cd lib/js-sdk && yarn lint

      - name: Build SDK dist/
        run: cd lib/js-sdk && yarn build
      
      