name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: "yarn"

      - name: Check for yarn.lock file
        run: |
          if [ ! -f "yarn.lock" ]; then
            echo "yarn.lock file not found."
            exit 1
          fi

      - name: Check network connectivity
        run: ping -c 5 google.com

      - name: Increase verbosity for yarn install
        run: yarn install --verbose

      - name: tsc Linting
        run: cd lib/js-sdk && yarn lint

      - name: Build SDK dist/
        run: cd lib/js-sdk && yarn build
