# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build:
    runs-on: arc-runner
    steps:
      - name: Action checkout.
        uses: actions/checkout@v3

      - name: Setting up Node.
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing yarn.
        run: |
          npm install --global yarn

      - name: Installing dependencies.
        run: |
          yarn install --frozen-lockfile

      - name: Running Tests.
        run: |
          yarn test

  publish-npm:
    needs: build
    runs-on: arc-runner
    steps:
      - name: Action checkout.
        uses: actions/checkout@v3

      - name: Setting up Node.
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Installing yarn.
        run: |
          npm install --global yarn

      - name: Installing dependencies.
        run: |
          yarn install --frozen-lockfile

      - name: Creating build.
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token2}}
